services:
  site-aimore:
    build: .
    restart: always
    container_name: portal-aimore
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aimore.rule=Host(`aimore.SEU-IP.sslip.io`)"
      - "traefik.http.services.aimore.loadbalancer.server.port=80"
